
DELETE http://localhost:8080/events/77126221-9c75-457f-9135-71c91275afba/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImplbGx5QGhleS5jb20iLCJleHAiOjE3Mjc4MTA5NjksInVzZXJJZCI6ImE3YzEwZDdiLWQzYzYtNGJlNS1hZjNhLWYyMTcyNjQyMzJhOCIsInVzZXJUeXBlIjoiYWRtaW4ifQ.0fIMMvg-YevXJGyqXjyhcWoUd8OLLzddpG_v9Z787pc