DELETE  http://localhost:8080/events/ad79d87a-9b72-4ccb-96ef-899722219e70
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFydC5kZXZAaGV5LmNvbSIsImV4cCI6MTcyNzc0Nzg2MCwidXNlcklkIjoiMTM4ZjVmMjktMGU5My00YTJjLTgyMjktMzQzY2ZkOTg2MDUwIiwidXNlclR5cGUiOiJhZG1pbiJ9.hS14vd7heaXiRJDxmOaHQBftlPVw5CBmqP26RbX96o4