
POST http://localhost:8080/events/77126221-9c75-457f-9135-71c91275afba/register
Authorization: eyJhbGciOiJIUzI1NiIsInRd5cCI6IkpXVCJ9.eyJlbWFpbCI6ImplbGx5QGhleS5jb20iLCJleHAiOjE3Mjc4MTAyMzgsInVzZXJJZCI6ImE3YzEwZDdiLWQzYzYtNGJlNS1hZjNhLWYyMTcyNjQyMzJhOCIsInVzZXJUeXBlIjoiYWRtaW4ifQ.WXjl9ApF4nbez5QLNjOSJJdoVRqTPrltZLr47xMWo_s